/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace STB_Modeling_Techniques.DEISProject.ODEDataModel.ThriftContract
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class TDDIMeasureUnion : TBase
  {
    private TDDIMeasure _Measure;
    private TDDIFaultToleranceMeasure _FaultToleranceMeasure;
    private TDDISecurityControl _SecurityControl;

    public TDDIMeasure Measure
    {
      get
      {
        return _Measure;
      }
      set
      {
        __isset.Measure = true;
        this._Measure = value;
      }
    }

    public TDDIFaultToleranceMeasure FaultToleranceMeasure
    {
      get
      {
        return _FaultToleranceMeasure;
      }
      set
      {
        __isset.FaultToleranceMeasure = true;
        this._FaultToleranceMeasure = value;
      }
    }

    public TDDISecurityControl SecurityControl
    {
      get
      {
        return _SecurityControl;
      }
      set
      {
        __isset.SecurityControl = true;
        this._SecurityControl = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool Measure;
      public bool FaultToleranceMeasure;
      public bool SecurityControl;
    }

    public TDDIMeasureUnion() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct) {
                Measure = new TDDIMeasure();
                Measure.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.Struct) {
                FaultToleranceMeasure = new TDDIFaultToleranceMeasure();
                FaultToleranceMeasure.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.Struct) {
                SecurityControl = new TDDISecurityControl();
                SecurityControl.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("TDDIMeasureUnion");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Measure != null && __isset.Measure) {
          field.Name = "Measure";
          field.Type = TType.Struct;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          Measure.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (FaultToleranceMeasure != null && __isset.FaultToleranceMeasure) {
          field.Name = "FaultToleranceMeasure";
          field.Type = TType.Struct;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          FaultToleranceMeasure.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (SecurityControl != null && __isset.SecurityControl) {
          field.Name = "SecurityControl";
          field.Type = TType.Struct;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          SecurityControl.Write(oprot);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("TDDIMeasureUnion(");
      bool __first = true;
      if (Measure != null && __isset.Measure) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Measure: ");
        __sb.Append(Measure== null ? "<null>" : Measure.ToString());
      }
      if (FaultToleranceMeasure != null && __isset.FaultToleranceMeasure) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("FaultToleranceMeasure: ");
        __sb.Append(FaultToleranceMeasure== null ? "<null>" : FaultToleranceMeasure.ToString());
      }
      if (SecurityControl != null && __isset.SecurityControl) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("SecurityControl: ");
        __sb.Append(SecurityControl);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
