/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace STB_Modeling_Techniques.DEISProject.ODEDataModel.ThriftContract
{
  public enum TDDIAssuranceCasePackageUnionType
  {
    ACPUTAssuranceCasePackage = 0,
    ACPUTAssuranceCasePackageInterface = 1,
    ACPUTAssuranceCasePackageBinding = 2,
  }
}
