/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace STB_Modeling_Techniques.DEISProject.ODEDataModel.ThriftContract
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class TDDIAbstractSACMElement : TBase
  {
    private TDDISACMElementUnion _UsedSACMElement;
    private TDDISACMElementUnionType _UsedSACMElementType;

    public TDDISACMElementUnion UsedSACMElement
    {
      get
      {
        return _UsedSACMElement;
      }
      set
      {
        __isset.UsedSACMElement = true;
        this._UsedSACMElement = value;
      }
    }

    /// <summary>
    /// 
    /// <seealso cref="TDDISACMElementUnionType"/>
    /// </summary>
    public TDDISACMElementUnionType UsedSACMElementType
    {
      get
      {
        return _UsedSACMElementType;
      }
      set
      {
        __isset.UsedSACMElementType = true;
        this._UsedSACMElementType = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool UsedSACMElement;
      public bool UsedSACMElementType;
    }

    public TDDIAbstractSACMElement() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct) {
                UsedSACMElement = new TDDISACMElementUnion();
                UsedSACMElement.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.I32) {
                UsedSACMElementType = (TDDISACMElementUnionType)iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("TDDIAbstractSACMElement");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (UsedSACMElement != null && __isset.UsedSACMElement) {
          field.Name = "UsedSACMElement";
          field.Type = TType.Struct;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          UsedSACMElement.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (__isset.UsedSACMElementType) {
          field.Name = "UsedSACMElementType";
          field.Type = TType.I32;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32((int)UsedSACMElementType);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("TDDIAbstractSACMElement(");
      bool __first = true;
      if (UsedSACMElement != null && __isset.UsedSACMElement) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("UsedSACMElement: ");
        __sb.Append(UsedSACMElement== null ? "<null>" : UsedSACMElement.ToString());
      }
      if (__isset.UsedSACMElementType) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("UsedSACMElementType: ");
        __sb.Append(UsedSACMElementType);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
