/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace STB_Modeling_Techniques.DEISProject.ODEDataModel.ThriftContract
{
  public enum TDDIArgumentAssetUnionType
  {
    AAUTAbstractAssertion = 0,
    AAUTArgumentReasoning = 1,
    AAUTArtifactReference = 2,
  }
}
