/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thriftContract;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2018-08-13")
public class TDDIOutputFailure implements org.apache.thrift.TBase<TDDIOutputFailure, TDDIOutputFailure._Fields>, java.io.Serializable, Cloneable, Comparable<TDDIOutputFailure> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TDDIOutputFailure");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("Id", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("Name", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField DESCRIPTION_FIELD_DESC = new org.apache.thrift.protocol.TField("Description", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField IS_CITATION_FIELD_DESC = new org.apache.thrift.protocol.TField("IsCitation", org.apache.thrift.protocol.TType.BOOL, (short)4);
  private static final org.apache.thrift.protocol.TField IS_ABSTRACT_FIELD_DESC = new org.apache.thrift.protocol.TField("IsAbstract", org.apache.thrift.protocol.TType.BOOL, (short)5);
  private static final org.apache.thrift.protocol.TField KEY_VALUE_MAPS_FIELD_DESC = new org.apache.thrift.protocol.TField("KeyValueMaps", org.apache.thrift.protocol.TType.LIST, (short)6);
  private static final org.apache.thrift.protocol.TField CITED_ELEMENT_FIELD_DESC = new org.apache.thrift.protocol.TField("CitedElement", org.apache.thrift.protocol.TType.STRUCT, (short)7);
  private static final org.apache.thrift.protocol.TField FAILURE_RATE_FIELD_DESC = new org.apache.thrift.protocol.TField("FailureRate", org.apache.thrift.protocol.TType.DOUBLE, (short)8);
  private static final org.apache.thrift.protocol.TField FAILURE_MODE_FIELD_DESC = new org.apache.thrift.protocol.TField("FailureMode", org.apache.thrift.protocol.TType.STRUCT, (short)9);
  private static final org.apache.thrift.protocol.TField PROBABILITY_DISTRIBUTION_FIELD_DESC = new org.apache.thrift.protocol.TField("ProbabilityDistribution", org.apache.thrift.protocol.TType.STRUCT, (short)10);
  private static final org.apache.thrift.protocol.TField MINIMAL_CUTSETS_FIELD_DESC = new org.apache.thrift.protocol.TField("MinimalCutsets", org.apache.thrift.protocol.TType.LIST, (short)11);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TDDIOutputFailureStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TDDIOutputFailureTupleSchemeFactory();

  public long Id; // required
  public java.lang.String Name; // required
  public java.lang.String Description; // required
  public boolean IsCitation; // required
  public boolean IsAbstract; // required
  public java.util.List<TDDIKeyValueMapRef> KeyValueMaps; // required
  public TDDIAbstractBaseElement CitedElement; // required
  public double FailureRate; // required
  public TDDIFailureMode FailureMode; // required
  public TDDIProbabilityDistribution ProbabilityDistribution; // required
  public java.util.List<TDDIMinimalCutset> MinimalCutsets; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "Id"),
    NAME((short)2, "Name"),
    DESCRIPTION((short)3, "Description"),
    IS_CITATION((short)4, "IsCitation"),
    IS_ABSTRACT((short)5, "IsAbstract"),
    KEY_VALUE_MAPS((short)6, "KeyValueMaps"),
    CITED_ELEMENT((short)7, "CitedElement"),
    FAILURE_RATE((short)8, "FailureRate"),
    FAILURE_MODE((short)9, "FailureMode"),
    PROBABILITY_DISTRIBUTION((short)10, "ProbabilityDistribution"),
    MINIMAL_CUTSETS((short)11, "MinimalCutsets");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // NAME
          return NAME;
        case 3: // DESCRIPTION
          return DESCRIPTION;
        case 4: // IS_CITATION
          return IS_CITATION;
        case 5: // IS_ABSTRACT
          return IS_ABSTRACT;
        case 6: // KEY_VALUE_MAPS
          return KEY_VALUE_MAPS;
        case 7: // CITED_ELEMENT
          return CITED_ELEMENT;
        case 8: // FAILURE_RATE
          return FAILURE_RATE;
        case 9: // FAILURE_MODE
          return FAILURE_MODE;
        case 10: // PROBABILITY_DISTRIBUTION
          return PROBABILITY_DISTRIBUTION;
        case 11: // MINIMAL_CUTSETS
          return MINIMAL_CUTSETS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ID_ISSET_ID = 0;
  private static final int __ISCITATION_ISSET_ID = 1;
  private static final int __ISABSTRACT_ISSET_ID = 2;
  private static final int __FAILURERATE_ISSET_ID = 3;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("Id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.NAME, new org.apache.thrift.meta_data.FieldMetaData("Name", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DESCRIPTION, new org.apache.thrift.meta_data.FieldMetaData("Description", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.IS_CITATION, new org.apache.thrift.meta_data.FieldMetaData("IsCitation", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.IS_ABSTRACT, new org.apache.thrift.meta_data.FieldMetaData("IsAbstract", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.KEY_VALUE_MAPS, new org.apache.thrift.meta_data.FieldMetaData("KeyValueMaps", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TDDIKeyValueMapRef.class))));
    tmpMap.put(_Fields.CITED_ELEMENT, new org.apache.thrift.meta_data.FieldMetaData("CitedElement", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TDDIAbstractBaseElement.class)));
    tmpMap.put(_Fields.FAILURE_RATE, new org.apache.thrift.meta_data.FieldMetaData("FailureRate", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.FAILURE_MODE, new org.apache.thrift.meta_data.FieldMetaData("FailureMode", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TDDIFailureMode.class)));
    tmpMap.put(_Fields.PROBABILITY_DISTRIBUTION, new org.apache.thrift.meta_data.FieldMetaData("ProbabilityDistribution", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TDDIProbabilityDistribution.class)));
    tmpMap.put(_Fields.MINIMAL_CUTSETS, new org.apache.thrift.meta_data.FieldMetaData("MinimalCutsets", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TDDIMinimalCutset.class))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TDDIOutputFailure.class, metaDataMap);
  }

  public TDDIOutputFailure() {
    this.Name = "";

    this.Description = "";

    this.IsCitation = false;

    this.IsAbstract = false;

    this.KeyValueMaps = new java.util.ArrayList<TDDIKeyValueMapRef>();

    this.MinimalCutsets = new java.util.ArrayList<TDDIMinimalCutset>();

  }

  public TDDIOutputFailure(
    long Id,
    java.lang.String Name,
    java.lang.String Description,
    boolean IsCitation,
    boolean IsAbstract,
    java.util.List<TDDIKeyValueMapRef> KeyValueMaps,
    TDDIAbstractBaseElement CitedElement,
    double FailureRate,
    TDDIFailureMode FailureMode,
    TDDIProbabilityDistribution ProbabilityDistribution,
    java.util.List<TDDIMinimalCutset> MinimalCutsets)
  {
    this();
    this.Id = Id;
    setIdIsSet(true);
    this.Name = Name;
    this.Description = Description;
    this.IsCitation = IsCitation;
    setIsCitationIsSet(true);
    this.IsAbstract = IsAbstract;
    setIsAbstractIsSet(true);
    this.KeyValueMaps = KeyValueMaps;
    this.CitedElement = CitedElement;
    this.FailureRate = FailureRate;
    setFailureRateIsSet(true);
    this.FailureMode = FailureMode;
    this.ProbabilityDistribution = ProbabilityDistribution;
    this.MinimalCutsets = MinimalCutsets;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TDDIOutputFailure(TDDIOutputFailure other) {
    __isset_bitfield = other.__isset_bitfield;
    this.Id = other.Id;
    if (other.isSetName()) {
      this.Name = other.Name;
    }
    if (other.isSetDescription()) {
      this.Description = other.Description;
    }
    this.IsCitation = other.IsCitation;
    this.IsAbstract = other.IsAbstract;
    if (other.isSetKeyValueMaps()) {
      java.util.List<TDDIKeyValueMapRef> __this__KeyValueMaps = new java.util.ArrayList<TDDIKeyValueMapRef>(other.KeyValueMaps.size());
      for (TDDIKeyValueMapRef other_element : other.KeyValueMaps) {
        __this__KeyValueMaps.add(new TDDIKeyValueMapRef(other_element));
      }
      this.KeyValueMaps = __this__KeyValueMaps;
    }
    if (other.isSetCitedElement()) {
      this.CitedElement = new TDDIAbstractBaseElement(other.CitedElement);
    }
    this.FailureRate = other.FailureRate;
    if (other.isSetFailureMode()) {
      this.FailureMode = new TDDIFailureMode(other.FailureMode);
    }
    if (other.isSetProbabilityDistribution()) {
      this.ProbabilityDistribution = new TDDIProbabilityDistribution(other.ProbabilityDistribution);
    }
    if (other.isSetMinimalCutsets()) {
      java.util.List<TDDIMinimalCutset> __this__MinimalCutsets = new java.util.ArrayList<TDDIMinimalCutset>(other.MinimalCutsets.size());
      for (TDDIMinimalCutset other_element : other.MinimalCutsets) {
        __this__MinimalCutsets.add(new TDDIMinimalCutset(other_element));
      }
      this.MinimalCutsets = __this__MinimalCutsets;
    }
  }

  public TDDIOutputFailure deepCopy() {
    return new TDDIOutputFailure(this);
  }

  @Override
  public void clear() {
    setIdIsSet(false);
    this.Id = 0;
    this.Name = "";

    this.Description = "";

    this.IsCitation = false;

    this.IsAbstract = false;

    this.KeyValueMaps = new java.util.ArrayList<TDDIKeyValueMapRef>();

    this.CitedElement = null;
    setFailureRateIsSet(false);
    this.FailureRate = 0.0;
    this.FailureMode = null;
    this.ProbabilityDistribution = null;
    this.MinimalCutsets = new java.util.ArrayList<TDDIMinimalCutset>();

  }

  public long getId() {
    return this.Id;
  }

  public TDDIOutputFailure setId(long Id) {
    this.Id = Id;
    setIdIsSet(true);
    return this;
  }

  public void unsetId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ID_ISSET_ID);
  }

  /** Returns true if field Id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ID_ISSET_ID);
  }

  public void setIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ID_ISSET_ID, value);
  }

  public java.lang.String getName() {
    return this.Name;
  }

  public TDDIOutputFailure setName(java.lang.String Name) {
    this.Name = Name;
    return this;
  }

  public void unsetName() {
    this.Name = null;
  }

  /** Returns true if field Name is set (has been assigned a value) and false otherwise */
  public boolean isSetName() {
    return this.Name != null;
  }

  public void setNameIsSet(boolean value) {
    if (!value) {
      this.Name = null;
    }
  }

  public java.lang.String getDescription() {
    return this.Description;
  }

  public TDDIOutputFailure setDescription(java.lang.String Description) {
    this.Description = Description;
    return this;
  }

  public void unsetDescription() {
    this.Description = null;
  }

  /** Returns true if field Description is set (has been assigned a value) and false otherwise */
  public boolean isSetDescription() {
    return this.Description != null;
  }

  public void setDescriptionIsSet(boolean value) {
    if (!value) {
      this.Description = null;
    }
  }

  public boolean isIsCitation() {
    return this.IsCitation;
  }

  public TDDIOutputFailure setIsCitation(boolean IsCitation) {
    this.IsCitation = IsCitation;
    setIsCitationIsSet(true);
    return this;
  }

  public void unsetIsCitation() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ISCITATION_ISSET_ID);
  }

  /** Returns true if field IsCitation is set (has been assigned a value) and false otherwise */
  public boolean isSetIsCitation() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ISCITATION_ISSET_ID);
  }

  public void setIsCitationIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ISCITATION_ISSET_ID, value);
  }

  public boolean isIsAbstract() {
    return this.IsAbstract;
  }

  public TDDIOutputFailure setIsAbstract(boolean IsAbstract) {
    this.IsAbstract = IsAbstract;
    setIsAbstractIsSet(true);
    return this;
  }

  public void unsetIsAbstract() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ISABSTRACT_ISSET_ID);
  }

  /** Returns true if field IsAbstract is set (has been assigned a value) and false otherwise */
  public boolean isSetIsAbstract() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ISABSTRACT_ISSET_ID);
  }

  public void setIsAbstractIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ISABSTRACT_ISSET_ID, value);
  }

  public int getKeyValueMapsSize() {
    return (this.KeyValueMaps == null) ? 0 : this.KeyValueMaps.size();
  }

  public java.util.Iterator<TDDIKeyValueMapRef> getKeyValueMapsIterator() {
    return (this.KeyValueMaps == null) ? null : this.KeyValueMaps.iterator();
  }

  public void addToKeyValueMaps(TDDIKeyValueMapRef elem) {
    if (this.KeyValueMaps == null) {
      this.KeyValueMaps = new java.util.ArrayList<TDDIKeyValueMapRef>();
    }
    this.KeyValueMaps.add(elem);
  }

  public java.util.List<TDDIKeyValueMapRef> getKeyValueMaps() {
    return this.KeyValueMaps;
  }

  public TDDIOutputFailure setKeyValueMaps(java.util.List<TDDIKeyValueMapRef> KeyValueMaps) {
    this.KeyValueMaps = KeyValueMaps;
    return this;
  }

  public void unsetKeyValueMaps() {
    this.KeyValueMaps = null;
  }

  /** Returns true if field KeyValueMaps is set (has been assigned a value) and false otherwise */
  public boolean isSetKeyValueMaps() {
    return this.KeyValueMaps != null;
  }

  public void setKeyValueMapsIsSet(boolean value) {
    if (!value) {
      this.KeyValueMaps = null;
    }
  }

  public TDDIAbstractBaseElement getCitedElement() {
    return this.CitedElement;
  }

  public TDDIOutputFailure setCitedElement(TDDIAbstractBaseElement CitedElement) {
    this.CitedElement = CitedElement;
    return this;
  }

  public void unsetCitedElement() {
    this.CitedElement = null;
  }

  /** Returns true if field CitedElement is set (has been assigned a value) and false otherwise */
  public boolean isSetCitedElement() {
    return this.CitedElement != null;
  }

  public void setCitedElementIsSet(boolean value) {
    if (!value) {
      this.CitedElement = null;
    }
  }

  public double getFailureRate() {
    return this.FailureRate;
  }

  public TDDIOutputFailure setFailureRate(double FailureRate) {
    this.FailureRate = FailureRate;
    setFailureRateIsSet(true);
    return this;
  }

  public void unsetFailureRate() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __FAILURERATE_ISSET_ID);
  }

  /** Returns true if field FailureRate is set (has been assigned a value) and false otherwise */
  public boolean isSetFailureRate() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __FAILURERATE_ISSET_ID);
  }

  public void setFailureRateIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __FAILURERATE_ISSET_ID, value);
  }

  public TDDIFailureMode getFailureMode() {
    return this.FailureMode;
  }

  public TDDIOutputFailure setFailureMode(TDDIFailureMode FailureMode) {
    this.FailureMode = FailureMode;
    return this;
  }

  public void unsetFailureMode() {
    this.FailureMode = null;
  }

  /** Returns true if field FailureMode is set (has been assigned a value) and false otherwise */
  public boolean isSetFailureMode() {
    return this.FailureMode != null;
  }

  public void setFailureModeIsSet(boolean value) {
    if (!value) {
      this.FailureMode = null;
    }
  }

  public TDDIProbabilityDistribution getProbabilityDistribution() {
    return this.ProbabilityDistribution;
  }

  public TDDIOutputFailure setProbabilityDistribution(TDDIProbabilityDistribution ProbabilityDistribution) {
    this.ProbabilityDistribution = ProbabilityDistribution;
    return this;
  }

  public void unsetProbabilityDistribution() {
    this.ProbabilityDistribution = null;
  }

  /** Returns true if field ProbabilityDistribution is set (has been assigned a value) and false otherwise */
  public boolean isSetProbabilityDistribution() {
    return this.ProbabilityDistribution != null;
  }

  public void setProbabilityDistributionIsSet(boolean value) {
    if (!value) {
      this.ProbabilityDistribution = null;
    }
  }

  public int getMinimalCutsetsSize() {
    return (this.MinimalCutsets == null) ? 0 : this.MinimalCutsets.size();
  }

  public java.util.Iterator<TDDIMinimalCutset> getMinimalCutsetsIterator() {
    return (this.MinimalCutsets == null) ? null : this.MinimalCutsets.iterator();
  }

  public void addToMinimalCutsets(TDDIMinimalCutset elem) {
    if (this.MinimalCutsets == null) {
      this.MinimalCutsets = new java.util.ArrayList<TDDIMinimalCutset>();
    }
    this.MinimalCutsets.add(elem);
  }

  public java.util.List<TDDIMinimalCutset> getMinimalCutsets() {
    return this.MinimalCutsets;
  }

  public TDDIOutputFailure setMinimalCutsets(java.util.List<TDDIMinimalCutset> MinimalCutsets) {
    this.MinimalCutsets = MinimalCutsets;
    return this;
  }

  public void unsetMinimalCutsets() {
    this.MinimalCutsets = null;
  }

  /** Returns true if field MinimalCutsets is set (has been assigned a value) and false otherwise */
  public boolean isSetMinimalCutsets() {
    return this.MinimalCutsets != null;
  }

  public void setMinimalCutsetsIsSet(boolean value) {
    if (!value) {
      this.MinimalCutsets = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((java.lang.Long)value);
      }
      break;

    case NAME:
      if (value == null) {
        unsetName();
      } else {
        setName((java.lang.String)value);
      }
      break;

    case DESCRIPTION:
      if (value == null) {
        unsetDescription();
      } else {
        setDescription((java.lang.String)value);
      }
      break;

    case IS_CITATION:
      if (value == null) {
        unsetIsCitation();
      } else {
        setIsCitation((java.lang.Boolean)value);
      }
      break;

    case IS_ABSTRACT:
      if (value == null) {
        unsetIsAbstract();
      } else {
        setIsAbstract((java.lang.Boolean)value);
      }
      break;

    case KEY_VALUE_MAPS:
      if (value == null) {
        unsetKeyValueMaps();
      } else {
        setKeyValueMaps((java.util.List<TDDIKeyValueMapRef>)value);
      }
      break;

    case CITED_ELEMENT:
      if (value == null) {
        unsetCitedElement();
      } else {
        setCitedElement((TDDIAbstractBaseElement)value);
      }
      break;

    case FAILURE_RATE:
      if (value == null) {
        unsetFailureRate();
      } else {
        setFailureRate((java.lang.Double)value);
      }
      break;

    case FAILURE_MODE:
      if (value == null) {
        unsetFailureMode();
      } else {
        setFailureMode((TDDIFailureMode)value);
      }
      break;

    case PROBABILITY_DISTRIBUTION:
      if (value == null) {
        unsetProbabilityDistribution();
      } else {
        setProbabilityDistribution((TDDIProbabilityDistribution)value);
      }
      break;

    case MINIMAL_CUTSETS:
      if (value == null) {
        unsetMinimalCutsets();
      } else {
        setMinimalCutsets((java.util.List<TDDIMinimalCutset>)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return getId();

    case NAME:
      return getName();

    case DESCRIPTION:
      return getDescription();

    case IS_CITATION:
      return isIsCitation();

    case IS_ABSTRACT:
      return isIsAbstract();

    case KEY_VALUE_MAPS:
      return getKeyValueMaps();

    case CITED_ELEMENT:
      return getCitedElement();

    case FAILURE_RATE:
      return getFailureRate();

    case FAILURE_MODE:
      return getFailureMode();

    case PROBABILITY_DISTRIBUTION:
      return getProbabilityDistribution();

    case MINIMAL_CUTSETS:
      return getMinimalCutsets();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case NAME:
      return isSetName();
    case DESCRIPTION:
      return isSetDescription();
    case IS_CITATION:
      return isSetIsCitation();
    case IS_ABSTRACT:
      return isSetIsAbstract();
    case KEY_VALUE_MAPS:
      return isSetKeyValueMaps();
    case CITED_ELEMENT:
      return isSetCitedElement();
    case FAILURE_RATE:
      return isSetFailureRate();
    case FAILURE_MODE:
      return isSetFailureMode();
    case PROBABILITY_DISTRIBUTION:
      return isSetProbabilityDistribution();
    case MINIMAL_CUTSETS:
      return isSetMinimalCutsets();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TDDIOutputFailure)
      return this.equals((TDDIOutputFailure)that);
    return false;
  }

  public boolean equals(TDDIOutputFailure that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_Id = true;
    boolean that_present_Id = true;
    if (this_present_Id || that_present_Id) {
      if (!(this_present_Id && that_present_Id))
        return false;
      if (this.Id != that.Id)
        return false;
    }

    boolean this_present_Name = true && this.isSetName();
    boolean that_present_Name = true && that.isSetName();
    if (this_present_Name || that_present_Name) {
      if (!(this_present_Name && that_present_Name))
        return false;
      if (!this.Name.equals(that.Name))
        return false;
    }

    boolean this_present_Description = true && this.isSetDescription();
    boolean that_present_Description = true && that.isSetDescription();
    if (this_present_Description || that_present_Description) {
      if (!(this_present_Description && that_present_Description))
        return false;
      if (!this.Description.equals(that.Description))
        return false;
    }

    boolean this_present_IsCitation = true;
    boolean that_present_IsCitation = true;
    if (this_present_IsCitation || that_present_IsCitation) {
      if (!(this_present_IsCitation && that_present_IsCitation))
        return false;
      if (this.IsCitation != that.IsCitation)
        return false;
    }

    boolean this_present_IsAbstract = true;
    boolean that_present_IsAbstract = true;
    if (this_present_IsAbstract || that_present_IsAbstract) {
      if (!(this_present_IsAbstract && that_present_IsAbstract))
        return false;
      if (this.IsAbstract != that.IsAbstract)
        return false;
    }

    boolean this_present_KeyValueMaps = true && this.isSetKeyValueMaps();
    boolean that_present_KeyValueMaps = true && that.isSetKeyValueMaps();
    if (this_present_KeyValueMaps || that_present_KeyValueMaps) {
      if (!(this_present_KeyValueMaps && that_present_KeyValueMaps))
        return false;
      if (!this.KeyValueMaps.equals(that.KeyValueMaps))
        return false;
    }

    boolean this_present_CitedElement = true && this.isSetCitedElement();
    boolean that_present_CitedElement = true && that.isSetCitedElement();
    if (this_present_CitedElement || that_present_CitedElement) {
      if (!(this_present_CitedElement && that_present_CitedElement))
        return false;
      if (!this.CitedElement.equals(that.CitedElement))
        return false;
    }

    boolean this_present_FailureRate = true;
    boolean that_present_FailureRate = true;
    if (this_present_FailureRate || that_present_FailureRate) {
      if (!(this_present_FailureRate && that_present_FailureRate))
        return false;
      if (this.FailureRate != that.FailureRate)
        return false;
    }

    boolean this_present_FailureMode = true && this.isSetFailureMode();
    boolean that_present_FailureMode = true && that.isSetFailureMode();
    if (this_present_FailureMode || that_present_FailureMode) {
      if (!(this_present_FailureMode && that_present_FailureMode))
        return false;
      if (!this.FailureMode.equals(that.FailureMode))
        return false;
    }

    boolean this_present_ProbabilityDistribution = true && this.isSetProbabilityDistribution();
    boolean that_present_ProbabilityDistribution = true && that.isSetProbabilityDistribution();
    if (this_present_ProbabilityDistribution || that_present_ProbabilityDistribution) {
      if (!(this_present_ProbabilityDistribution && that_present_ProbabilityDistribution))
        return false;
      if (!this.ProbabilityDistribution.equals(that.ProbabilityDistribution))
        return false;
    }

    boolean this_present_MinimalCutsets = true && this.isSetMinimalCutsets();
    boolean that_present_MinimalCutsets = true && that.isSetMinimalCutsets();
    if (this_present_MinimalCutsets || that_present_MinimalCutsets) {
      if (!(this_present_MinimalCutsets && that_present_MinimalCutsets))
        return false;
      if (!this.MinimalCutsets.equals(that.MinimalCutsets))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(Id);

    hashCode = hashCode * 8191 + ((isSetName()) ? 131071 : 524287);
    if (isSetName())
      hashCode = hashCode * 8191 + Name.hashCode();

    hashCode = hashCode * 8191 + ((isSetDescription()) ? 131071 : 524287);
    if (isSetDescription())
      hashCode = hashCode * 8191 + Description.hashCode();

    hashCode = hashCode * 8191 + ((IsCitation) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((IsAbstract) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isSetKeyValueMaps()) ? 131071 : 524287);
    if (isSetKeyValueMaps())
      hashCode = hashCode * 8191 + KeyValueMaps.hashCode();

    hashCode = hashCode * 8191 + ((isSetCitedElement()) ? 131071 : 524287);
    if (isSetCitedElement())
      hashCode = hashCode * 8191 + CitedElement.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(FailureRate);

    hashCode = hashCode * 8191 + ((isSetFailureMode()) ? 131071 : 524287);
    if (isSetFailureMode())
      hashCode = hashCode * 8191 + FailureMode.hashCode();

    hashCode = hashCode * 8191 + ((isSetProbabilityDistribution()) ? 131071 : 524287);
    if (isSetProbabilityDistribution())
      hashCode = hashCode * 8191 + ProbabilityDistribution.hashCode();

    hashCode = hashCode * 8191 + ((isSetMinimalCutsets()) ? 131071 : 524287);
    if (isSetMinimalCutsets())
      hashCode = hashCode * 8191 + MinimalCutsets.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(TDDIOutputFailure other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetId()).compareTo(other.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Id, other.Id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetName()).compareTo(other.isSetName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Name, other.Name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetDescription()).compareTo(other.isSetDescription());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDescription()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Description, other.Description);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetIsCitation()).compareTo(other.isSetIsCitation());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIsCitation()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.IsCitation, other.IsCitation);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetIsAbstract()).compareTo(other.isSetIsAbstract());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIsAbstract()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.IsAbstract, other.IsAbstract);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetKeyValueMaps()).compareTo(other.isSetKeyValueMaps());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetKeyValueMaps()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.KeyValueMaps, other.KeyValueMaps);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCitedElement()).compareTo(other.isSetCitedElement());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCitedElement()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.CitedElement, other.CitedElement);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetFailureRate()).compareTo(other.isSetFailureRate());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFailureRate()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.FailureRate, other.FailureRate);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetFailureMode()).compareTo(other.isSetFailureMode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFailureMode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.FailureMode, other.FailureMode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetProbabilityDistribution()).compareTo(other.isSetProbabilityDistribution());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProbabilityDistribution()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ProbabilityDistribution, other.ProbabilityDistribution);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetMinimalCutsets()).compareTo(other.isSetMinimalCutsets());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMinimalCutsets()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.MinimalCutsets, other.MinimalCutsets);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TDDIOutputFailure(");
    boolean first = true;

    sb.append("Id:");
    sb.append(this.Id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("Name:");
    if (this.Name == null) {
      sb.append("null");
    } else {
      sb.append(this.Name);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("Description:");
    if (this.Description == null) {
      sb.append("null");
    } else {
      sb.append(this.Description);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("IsCitation:");
    sb.append(this.IsCitation);
    first = false;
    if (!first) sb.append(", ");
    sb.append("IsAbstract:");
    sb.append(this.IsAbstract);
    first = false;
    if (!first) sb.append(", ");
    sb.append("KeyValueMaps:");
    if (this.KeyValueMaps == null) {
      sb.append("null");
    } else {
      sb.append(this.KeyValueMaps);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("CitedElement:");
    if (this.CitedElement == null) {
      sb.append("null");
    } else {
      sb.append(this.CitedElement);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("FailureRate:");
    sb.append(this.FailureRate);
    first = false;
    if (!first) sb.append(", ");
    sb.append("FailureMode:");
    if (this.FailureMode == null) {
      sb.append("null");
    } else {
      sb.append(this.FailureMode);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("ProbabilityDistribution:");
    if (this.ProbabilityDistribution == null) {
      sb.append("null");
    } else {
      sb.append(this.ProbabilityDistribution);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("MinimalCutsets:");
    if (this.MinimalCutsets == null) {
      sb.append("null");
    } else {
      sb.append(this.MinimalCutsets);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (CitedElement != null) {
      CitedElement.validate();
    }
    if (FailureMode != null) {
      FailureMode.validate();
    }
    if (ProbabilityDistribution != null) {
      ProbabilityDistribution.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TDDIOutputFailureStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TDDIOutputFailureStandardScheme getScheme() {
      return new TDDIOutputFailureStandardScheme();
    }
  }

  private static class TDDIOutputFailureStandardScheme extends org.apache.thrift.scheme.StandardScheme<TDDIOutputFailure> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TDDIOutputFailure struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.Id = iprot.readI64();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.Name = iprot.readString();
              struct.setNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // DESCRIPTION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.Description = iprot.readString();
              struct.setDescriptionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // IS_CITATION
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.IsCitation = iprot.readBool();
              struct.setIsCitationIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // IS_ABSTRACT
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.IsAbstract = iprot.readBool();
              struct.setIsAbstractIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // KEY_VALUE_MAPS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list896 = iprot.readListBegin();
                struct.KeyValueMaps = new java.util.ArrayList<TDDIKeyValueMapRef>(_list896.size);
                TDDIKeyValueMapRef _elem897;
                for (int _i898 = 0; _i898 < _list896.size; ++_i898)
                {
                  _elem897 = new TDDIKeyValueMapRef();
                  _elem897.read(iprot);
                  struct.KeyValueMaps.add(_elem897);
                }
                iprot.readListEnd();
              }
              struct.setKeyValueMapsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // CITED_ELEMENT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.CitedElement = new TDDIAbstractBaseElement();
              struct.CitedElement.read(iprot);
              struct.setCitedElementIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // FAILURE_RATE
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.FailureRate = iprot.readDouble();
              struct.setFailureRateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // FAILURE_MODE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.FailureMode = new TDDIFailureMode();
              struct.FailureMode.read(iprot);
              struct.setFailureModeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // PROBABILITY_DISTRIBUTION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.ProbabilityDistribution = new TDDIProbabilityDistribution();
              struct.ProbabilityDistribution.read(iprot);
              struct.setProbabilityDistributionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // MINIMAL_CUTSETS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list899 = iprot.readListBegin();
                struct.MinimalCutsets = new java.util.ArrayList<TDDIMinimalCutset>(_list899.size);
                TDDIMinimalCutset _elem900;
                for (int _i901 = 0; _i901 < _list899.size; ++_i901)
                {
                  _elem900 = new TDDIMinimalCutset();
                  _elem900.read(iprot);
                  struct.MinimalCutsets.add(_elem900);
                }
                iprot.readListEnd();
              }
              struct.setMinimalCutsetsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TDDIOutputFailure struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ID_FIELD_DESC);
      oprot.writeI64(struct.Id);
      oprot.writeFieldEnd();
      if (struct.Name != null) {
        oprot.writeFieldBegin(NAME_FIELD_DESC);
        oprot.writeString(struct.Name);
        oprot.writeFieldEnd();
      }
      if (struct.Description != null) {
        oprot.writeFieldBegin(DESCRIPTION_FIELD_DESC);
        oprot.writeString(struct.Description);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(IS_CITATION_FIELD_DESC);
      oprot.writeBool(struct.IsCitation);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(IS_ABSTRACT_FIELD_DESC);
      oprot.writeBool(struct.IsAbstract);
      oprot.writeFieldEnd();
      if (struct.KeyValueMaps != null) {
        oprot.writeFieldBegin(KEY_VALUE_MAPS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.KeyValueMaps.size()));
          for (TDDIKeyValueMapRef _iter902 : struct.KeyValueMaps)
          {
            _iter902.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.CitedElement != null) {
        oprot.writeFieldBegin(CITED_ELEMENT_FIELD_DESC);
        struct.CitedElement.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(FAILURE_RATE_FIELD_DESC);
      oprot.writeDouble(struct.FailureRate);
      oprot.writeFieldEnd();
      if (struct.FailureMode != null) {
        oprot.writeFieldBegin(FAILURE_MODE_FIELD_DESC);
        struct.FailureMode.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.ProbabilityDistribution != null) {
        oprot.writeFieldBegin(PROBABILITY_DISTRIBUTION_FIELD_DESC);
        struct.ProbabilityDistribution.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.MinimalCutsets != null) {
        oprot.writeFieldBegin(MINIMAL_CUTSETS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.MinimalCutsets.size()));
          for (TDDIMinimalCutset _iter903 : struct.MinimalCutsets)
          {
            _iter903.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TDDIOutputFailureTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TDDIOutputFailureTupleScheme getScheme() {
      return new TDDIOutputFailureTupleScheme();
    }
  }

  private static class TDDIOutputFailureTupleScheme extends org.apache.thrift.scheme.TupleScheme<TDDIOutputFailure> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TDDIOutputFailure struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetId()) {
        optionals.set(0);
      }
      if (struct.isSetName()) {
        optionals.set(1);
      }
      if (struct.isSetDescription()) {
        optionals.set(2);
      }
      if (struct.isSetIsCitation()) {
        optionals.set(3);
      }
      if (struct.isSetIsAbstract()) {
        optionals.set(4);
      }
      if (struct.isSetKeyValueMaps()) {
        optionals.set(5);
      }
      if (struct.isSetCitedElement()) {
        optionals.set(6);
      }
      if (struct.isSetFailureRate()) {
        optionals.set(7);
      }
      if (struct.isSetFailureMode()) {
        optionals.set(8);
      }
      if (struct.isSetProbabilityDistribution()) {
        optionals.set(9);
      }
      if (struct.isSetMinimalCutsets()) {
        optionals.set(10);
      }
      oprot.writeBitSet(optionals, 11);
      if (struct.isSetId()) {
        oprot.writeI64(struct.Id);
      }
      if (struct.isSetName()) {
        oprot.writeString(struct.Name);
      }
      if (struct.isSetDescription()) {
        oprot.writeString(struct.Description);
      }
      if (struct.isSetIsCitation()) {
        oprot.writeBool(struct.IsCitation);
      }
      if (struct.isSetIsAbstract()) {
        oprot.writeBool(struct.IsAbstract);
      }
      if (struct.isSetKeyValueMaps()) {
        {
          oprot.writeI32(struct.KeyValueMaps.size());
          for (TDDIKeyValueMapRef _iter904 : struct.KeyValueMaps)
          {
            _iter904.write(oprot);
          }
        }
      }
      if (struct.isSetCitedElement()) {
        struct.CitedElement.write(oprot);
      }
      if (struct.isSetFailureRate()) {
        oprot.writeDouble(struct.FailureRate);
      }
      if (struct.isSetFailureMode()) {
        struct.FailureMode.write(oprot);
      }
      if (struct.isSetProbabilityDistribution()) {
        struct.ProbabilityDistribution.write(oprot);
      }
      if (struct.isSetMinimalCutsets()) {
        {
          oprot.writeI32(struct.MinimalCutsets.size());
          for (TDDIMinimalCutset _iter905 : struct.MinimalCutsets)
          {
            _iter905.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TDDIOutputFailure struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(11);
      if (incoming.get(0)) {
        struct.Id = iprot.readI64();
        struct.setIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.Name = iprot.readString();
        struct.setNameIsSet(true);
      }
      if (incoming.get(2)) {
        struct.Description = iprot.readString();
        struct.setDescriptionIsSet(true);
      }
      if (incoming.get(3)) {
        struct.IsCitation = iprot.readBool();
        struct.setIsCitationIsSet(true);
      }
      if (incoming.get(4)) {
        struct.IsAbstract = iprot.readBool();
        struct.setIsAbstractIsSet(true);
      }
      if (incoming.get(5)) {
        {
          org.apache.thrift.protocol.TList _list906 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.KeyValueMaps = new java.util.ArrayList<TDDIKeyValueMapRef>(_list906.size);
          TDDIKeyValueMapRef _elem907;
          for (int _i908 = 0; _i908 < _list906.size; ++_i908)
          {
            _elem907 = new TDDIKeyValueMapRef();
            _elem907.read(iprot);
            struct.KeyValueMaps.add(_elem907);
          }
        }
        struct.setKeyValueMapsIsSet(true);
      }
      if (incoming.get(6)) {
        struct.CitedElement = new TDDIAbstractBaseElement();
        struct.CitedElement.read(iprot);
        struct.setCitedElementIsSet(true);
      }
      if (incoming.get(7)) {
        struct.FailureRate = iprot.readDouble();
        struct.setFailureRateIsSet(true);
      }
      if (incoming.get(8)) {
        struct.FailureMode = new TDDIFailureMode();
        struct.FailureMode.read(iprot);
        struct.setFailureModeIsSet(true);
      }
      if (incoming.get(9)) {
        struct.ProbabilityDistribution = new TDDIProbabilityDistribution();
        struct.ProbabilityDistribution.read(iprot);
        struct.setProbabilityDistributionIsSet(true);
      }
      if (incoming.get(10)) {
        {
          org.apache.thrift.protocol.TList _list909 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.MinimalCutsets = new java.util.ArrayList<TDDIMinimalCutset>(_list909.size);
          TDDIMinimalCutset _elem910;
          for (int _i911 = 0; _i911 < _list909.size; ++_i911)
          {
            _elem910 = new TDDIMinimalCutset();
            _elem910.read(iprot);
            struct.MinimalCutsets.add(_elem910);
          }
        }
        struct.setMinimalCutsetsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

