/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace STB_Modeling_Techniques.DEISProject.ODEDataModel.ThriftContract
{
  public enum TDDIAssertionDeclaration
  {
    ADAsserted = 0,
    ADNeedsSupport = 1,
    ADAssumed = 2,
    ADAxiomatic = 3,
    ADDefeated = 4,
    ADAsCited = 5,
  }
}
