/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace STB_Modeling_Techniques.DEISProject.ODEDataModel.ThriftContract
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class TDDIAbstractInterfaceFailure : TBase
  {
    private TDDIInterfaceFailureUnion _UsedInterfaceFailure;
    private TDDIInterfaceFailureUnionType _UsedInterfaceFailureType;

    public TDDIInterfaceFailureUnion UsedInterfaceFailure
    {
      get
      {
        return _UsedInterfaceFailure;
      }
      set
      {
        __isset.UsedInterfaceFailure = true;
        this._UsedInterfaceFailure = value;
      }
    }

    /// <summary>
    /// 
    /// <seealso cref="TDDIInterfaceFailureUnionType"/>
    /// </summary>
    public TDDIInterfaceFailureUnionType UsedInterfaceFailureType
    {
      get
      {
        return _UsedInterfaceFailureType;
      }
      set
      {
        __isset.UsedInterfaceFailureType = true;
        this._UsedInterfaceFailureType = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool UsedInterfaceFailure;
      public bool UsedInterfaceFailureType;
    }

    public TDDIAbstractInterfaceFailure() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct) {
                UsedInterfaceFailure = new TDDIInterfaceFailureUnion();
                UsedInterfaceFailure.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.I32) {
                UsedInterfaceFailureType = (TDDIInterfaceFailureUnionType)iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("TDDIAbstractInterfaceFailure");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (UsedInterfaceFailure != null && __isset.UsedInterfaceFailure) {
          field.Name = "UsedInterfaceFailure";
          field.Type = TType.Struct;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          UsedInterfaceFailure.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (__isset.UsedInterfaceFailureType) {
          field.Name = "UsedInterfaceFailureType";
          field.Type = TType.I32;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32((int)UsedInterfaceFailureType);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("TDDIAbstractInterfaceFailure(");
      bool __first = true;
      if (UsedInterfaceFailure != null && __isset.UsedInterfaceFailure) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("UsedInterfaceFailure: ");
        __sb.Append(UsedInterfaceFailure== null ? "<null>" : UsedInterfaceFailure.ToString());
      }
      if (__isset.UsedInterfaceFailureType) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("UsedInterfaceFailureType: ");
        __sb.Append(UsedInterfaceFailureType);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
